version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./contenido_php:/usr/share/nginx/html
    depends_on:
      - php

  php:
    image: php:fpm

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mi_basedatos
